### PR TITLE
Solana AMM tutorial

### PR DESCRIPTION
**Pull request by Osawejustice**
Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request", make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8) and reviewed the [Sample Tutorial Structure](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d). 

Please confirm the following before submitting your tutorial for review - 

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [X] The title of the Pull Request matches the title of my tutorial.
- [X] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [X] I've [proofread the tutorial](https://grammarly.com) for spelling and grammar mistakes.
- [X] I've run a linter & prettifier to format my code blocks.
- [X] I've thoroughly explained the code, with inline code comments and text explanations.
- [X] I've run the tutorial to test it and the code works.

**NOTE**: We cannot review your Pull Request if it does not meet the standard outlined above.

### CODE REVIEW

**Comment by yash-sharma1** [comment]
Hey @Osawejustice 
Thanks for submitting the PR. I had a look at the tutorial and it seems so basic there's no code, no explanation of the steps and oyster-swap program as well as there's no mention about creating the front-end. Please refer to this tutorial to get a high-level understanding of the explanation, steps, and content - **[Build a Solana Wallet](https://learn.figment.io/tutorials/solana-wallet-intro)**

**Comment by Osawejustice** [comment]
Thank You For the Feedback .

I'll immediately make the necessary improvements to the tutorial and make
another pull request.


Thank you so much

**Comment by yash-sharma1** [comment]
Thanks for responding back. Here's my feedback on the tutorial -

- The tutorial is just a walkthrough of the steps to run the Oyster-swap repo on local by making some small changes in the address and fee but we expect you to build an AMM on Solana from scratch you're allowed to use the oyster-swap repo as a reference but not completely copy-paste that. 
- In the tutorial, you should explain the implementation of the smart contract, adding liquidity, swap, withdrawal functionalities briefly from scratch.
- You should add steps to build your own front end from scratch similar to Raydium and provide its code & explanation in the tutorial.
- You should add a live demo video of the working AMM on testnet in the tutorial.
- For ref, must check to **[Create an Automated Market Maker (AMM) on Avalanche tutorial](https://learn.figment.io/tutorials/create-an-amm-on-avalanche)**.

We expect you to make all these changes before the initial review. Let me know if you have any questions.

**Comment by yash-sharma1** [comment]
Hey @Osawejustice 
I'm writing this to inform you that recently I got to know some of the functionalities of swapping & liquidity are deprecated in the Oyster Swap program and our team is working on the similar one so in reference to that I'm closing this PR and looking forward working to with you on new tutorial topics. I'll keep you informed of the same on email.

**Pull request closed without merging**
